#VARIOUS ACCOUNT DATA AND CONSTANTS

#Metatrader5
MT5_ACCOUNT = "7363894"
MT5_PASSWORD = "TesiLaurea25!"
MT5_SERVER = "FirstPrudentialMarkets-Demo"
MAGIC_NUMBER = "09031994"

#Symbols list
SYMBOLS = ["^NDX", "^GDAXI"]