#VARIOUS ACCOUNT DATA AND CONSTANTS

#Metatrader5
MT5_ACCOUNT = "77777777"
MT5_PASSWORD = "password"
MT5_SERVER = "FirstPrudentialMarkets-Demo"
MAGIC_NUMBER = "09031994"

#Symbols list
SYMBOLS = ["^NDX", "^GDAXI"]